In [1]:
import jax.numpy as jnp
from jax import jacfwd

In [2]:
def f(x):
    return jnp.dot(x, jnp.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]))

x = jnp.array([1., 2., 3.])
jacobian = jacfwd(f)(x)

print(jacobian)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [3]:
f(x)

DeviceArray([30., 36., 42.], dtype=float32)

In [4]:
jnp.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

DeviceArray([[1., 2., 3.],
             [4., 5., 6.],
             [7., 8., 9.]], dtype=float32)

In [5]:
x = jnp.array([1, 2, 3, 4, 5])
rolling_sum = jnp.cumsum(x)

print(rolling_sum)

[ 1  3  6 10 15]
